<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>PHP Frameworks Speed Benchmark </title>
        <link rel="stylesheet" type="text/css" href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/css/main.css" />
    </head>

    <body>

        <div id="menu"><?php include_once $_SERVER['DOCUMENT_ROOT'].'/menu.php'; ?></div>

        <div class="body">
            <div class="container" id="page">
                <?php echo $this->layout()->content ?>
            </div>
        </div>

    </body>
</html>