<div class="block-wrapper">
    <h1>Опис на методите</h1>
    <div class="block-description">
        <p>Опис на методите:</p>
        <ul>
            <li>
                <strong>find()</strong>
                - 
                <span>Прима цел број (примарен клуч) како параметар а како резултат враќа еден ред од база.</span>
            </li>
            <li>
                <strong>fetchRow()</strong>
                - 
                <span>Прима атрибут како параметар а како резултат враќа еден ред од база.</span>
            </li>
        </ul>
    </div>
    <div class="block-chart">
        <div id="chart1-zend"></div>
    </div>
</div>

<div id="find-fetchRow" class="block-wrapper">
    <h2>find() & fetchRow()</h2>
    <div class="block-description">
        <p>Постојат случаеви во кои и двата метода можеме да ги користеме за иста цел 
            (Пример, сакаме да извадеме ред од база кога го имаме примарниот клуч).</p>
        <p>Од извршените тестови можеме да заклучиме дека во овие случаеви подобро е
            да го користиме методот find() одколку fetchRow() бидејки е многу побрз.</p>
    </div>
    <div class="block-chart">
        <div id="chart1-zend"></div>
    </div>
</div>

<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    
    google.setOnLoadCallback(drawChart);
    
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Database Type', 'find()', 'fetchRow()'],
            ['Small', <?php echo $this->find_zend['small']; ?>, <?php echo $this->fetchRow_zend['small']; ?>],
            ['Medium', <?php echo $this->find_zend['medium']; ?>, <?php echo $this->fetchRow_zend['medium']; ?>],
            ['Large', <?php echo $this->find_zend['large']; ?>, <?php echo $this->fetchRow_zend['large']; ?>]
        ]);
        var options = {
            title: 'find() & fetchRow() in Zend',
            hAxis: {title: 'Table Size', titleTextStyle: {color: 'red'}}
        };
        var chart = new google.visualization.ColumnChart(document.getElementById('chart1-zend'));
        chart.draw(data, options);
    }
</script>